development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  username: 
  password:

test: &TEST
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST